=== FearPingWin/L2CraciaFinal/l2jfree-datapack/data/stats/skills/skills.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!-- Root -->
<!ELEMENT list (skill)*>

<!-- Skill -->
<!ATTLIST skill id CDATA #REQUIRED>
<!ATTLIST skill name CDATA #REQUIRED>
<!ATTLIST skill levels CDATA #REQUIRED>
<!ATTLIST skill enchantLevels1 CDATA #IMPLIED>
<!ATTLIST skill enchantLevels2 CDATA #IMPLIED>
<!ATTLIST skill enchantLevels3 CDATA #IMPLIED>
<!ATTLIST skill enchantLevels4 CDATA #IMPLIED>
<!ATTLIST skill enchantLevels5 CDATA #IMPLIED>
<!ELEMENT skill ((table|set|enchant1|enchant2|enchant3|enchant4|enchant5)*,cond?,enchant1cond?,enchant2cond?,enchant3cond?,enchant4cond?,enchant5cond?,for?,enchant1for?,enchant2for?,enchant3for?,enchant4for?,enchant5for?)>

<!-- Table -->
<!ATTLIST table name CDATA #REQUIRED>
<!ELEMENT table (#PCDATA)>

<!-- Property -->
<!ATTLIST set      name CDATA #IMPLIED> <!-- overlapping with stats -->
<!ATTLIST enchant1 name CDATA #REQUIRED>
<!ATTLIST enchant2 name CDATA #REQUIRED>
<!ATTLIST enchant3 name CDATA #REQUIRED>
<!ATTLIST enchant4 name CDATA #REQUIRED>
<!ATTLIST enchant5 name CDATA #REQUIRED>
<!ATTLIST set      val CDATA #REQUIRED>
<!ATTLIST enchant1 val CDATA #REQUIRED>
<!ATTLIST enchant2 val CDATA #REQUIRED>
<!ATTLIST enchant3 val CDATA #REQUIRED>
<!ATTLIST enchant4 val CDATA #REQUIRED>
<!ATTLIST enchant5 val CDATA #REQUIRED>
<!-- <!ELEMENT set      EMPTY> --> <!-- overlapping with stats -->
<!ELEMENT enchant1 EMPTY>
<!ELEMENT enchant2 EMPTY>
<!ELEMENT enchant3 EMPTY>
<!ELEMENT enchant4 EMPTY>
<!ELEMENT enchant5 EMPTY>

<!-- Template -->
<!ELEMENT for         (effect*|(set|add|sub|mul|div|basemul)+)> <!-- TODO -->
<!ELEMENT enchant1for (effect*|(set|add|sub|mul|div|basemul)+)> <!-- TODO -->
<!ELEMENT enchant2for (effect*|(set|add|sub|mul|div|basemul)+)> <!-- TODO -->
<!ELEMENT enchant3for (effect*|(set|add|sub|mul|div|basemul)+)> <!-- TODO -->
<!ELEMENT enchant4for (effect*|(set|add|sub|mul|div|basemul)+)> <!-- TODO -->
<!ELEMENT enchant5for (effect*|(set|add|sub|mul|div|basemul)+)> <!-- TODO -->

<!-- Condition -->
<!ATTLIST cond         msg CDATA #IMPLIED>
<!ATTLIST enchant1cond msg CDATA #IMPLIED>
<!ATTLIST enchant2cond msg CDATA #IMPLIED>
<!ATTLIST enchant3cond msg CDATA #IMPLIED>
<!ATTLIST enchant4cond msg CDATA #IMPLIED>
<!ATTLIST enchant5cond msg CDATA #IMPLIED>
<!ATTLIST cond         msgId CDATA #IMPLIED>
<!ATTLIST enchant1cond msgId CDATA #IMPLIED>
<!ATTLIST enchant2cond msgId CDATA #IMPLIED>
<!ATTLIST enchant3cond msgId CDATA #IMPLIED>
<!ATTLIST enchant4cond msgId CDATA #IMPLIED>
<!ATTLIST enchant5cond msgId CDATA #IMPLIED>
<!ELEMENT cond         (and|or|not|player|target|using|game)>
<!ELEMENT enchant1cond (and|or|not|player|target|using|game)>
<!ELEMENT enchant2cond (and|or|not|player|target|using|game)>
<!ELEMENT enchant3cond (and|or|not|player|target|using|game)>
<!ELEMENT enchant4cond (and|or|not|player|target|using|game)>
<!ELEMENT enchant5cond (and|or|not|player|target|using|game)>

<!-- Effect -->
<!ATTLIST effect name CDATA #REQUIRED>
<!ATTLIST effect count CDATA #IMPLIED>
<!ATTLIST effect time CDATA #REQUIRED>
<!ATTLIST effect self (1) #IMPLIED>
<!ATTLIST effect noicon (1) #IMPLIED>
<!ATTLIST effect val CDATA #REQUIRED>
<!ATTLIST effect abnormal (bleeding|poison|redcircle|ice|wind|flame|stun|mute|root|bighead|stealth|earthquake|invul) #IMPLIED>
<!ATTLIST effect stackType CDATA #IMPLIED>
<!ATTLIST effect stackOrder CDATA #IMPLIED>
<!ELEMENT effect (cond?,(set|add|sub|mul|div|basemul)*)> <!-- TODO: cond? -->

<!-- Stat -->
<!ATTLIST set     stat CDATA #IMPLIED> <!-- overlapping with properties -->
<!ATTLIST add     stat CDATA #REQUIRED>
<!ATTLIST sub     stat CDATA #REQUIRED>
<!ATTLIST mul     stat CDATA #REQUIRED>
<!ATTLIST div     stat CDATA #REQUIRED>
<!ATTLIST basemul stat CDATA #REQUIRED>
<!ATTLIST set     order (0x08|0x99) #IMPLIED> <!-- one level to set it before calculations, and another to set if after --> <!-- overlapping with properties -->
<!ATTLIST add     order (0x10|0x40) #REQUIRED> <!-- same level for add/sub -->
<!ATTLIST sub     order (0x10|0x40) #REQUIRED> <!-- same level for add/sub -->
<!ATTLIST mul     order (0x30) #REQUIRED> <!-- same level for mul/div -->
<!ATTLIST div     order (0x30) #REQUIRED> <!-- same level for mul/div -->
<!ATTLIST basemul order (0x30) #REQUIRED> <!-- same level with mul/div -> COULD CAUSE PROBLEMS -> SHOULD BE CHANGED -->
<!ATTLIST set     val CDATA #REQUIRED>
<!ATTLIST add     val CDATA #REQUIRED>
<!ATTLIST sub     val CDATA #REQUIRED>
<!ATTLIST mul     val CDATA #REQUIRED>
<!ATTLIST div     val CDATA #REQUIRED>
<!ATTLIST basemul val CDATA #REQUIRED>
<!ELEMENT set     (and|or|not|player|target|using|game)?> <!-- overlapping with properties -->
<!ELEMENT add     (and|or|not|player|target|using|game)?>
<!ELEMENT sub     (and|or|not|player|target|using|game)?>
<!ELEMENT mul     (and|or|not|player|target|using|game)?>
<!ELEMENT div     (and|or|not|player|target|using|game)?>
<!ELEMENT basemul (and|or|not|player|target|using|game)?>

<!-- Logic -->
<!ELEMENT and ((and|or|not|player|target|using|game)+)> <!-- TODO: make sure <and> tags contains multiple elements -->
<!-- <!ELEMENT and ((and|or|not|player|target|using|game),(and|or|not|player|target|using|game)+)> -->
<!ELEMENT or  ((and|or|not|player|target|using|game),(and|or|not|player|target|using|game)+)>
<!ELEMENT not (and|or|not|player|target|using|game)>

<!-- Conditions -->
<!ATTLIST player skill (true|false) #IMPLIED>
<!ATTLIST player race (Human|Elf|Darkelf|Orc|Dwarf|Kamael) #IMPLIED>
<!ATTLIST player level CDATA #IMPLIED>
<!ATTLIST player resting (true|false) #IMPLIED>
<!ATTLIST player moving (true|false) #IMPLIED>
<!ATTLIST player running (true|false) #IMPLIED>
<!ATTLIST player walking (true|false) #IMPLIED>
<!ATTLIST player behind (true|false) #IMPLIED>
<!ATTLIST player front (true|false) #IMPLIED>
<!ATTLIST player chaotic (true|false) #IMPLIED>
<!ATTLIST player olympiad (true|false) #IMPLIED>
<!ATTLIST player flying (true|false) #IMPLIED>
<!ATTLIST player hp CDATA #IMPLIED>
<!ATTLIST player mp CDATA #IMPLIED>
<!ATTLIST player cp CDATA #IMPLIED>
<!ATTLIST player attack_stance (true|false) #IMPLIED>
<!ATTLIST player grade CDATA #IMPLIED>
<!ATTLIST player siegezone CDATA #IMPLIED>
<!ATTLIST player battle_force (2|3) #IMPLIED>
<!ATTLIST player spell_force (2|3) #IMPLIED>
<!ATTLIST player weight CDATA #IMPLIED>
<!ATTLIST player invSize CDATA #IMPLIED>
<!ATTLIST player pledgeClass CDATA #IMPLIED>
<!ATTLIST player clanHall CDATA #IMPLIED>
<!ATTLIST player fort CDATA #IMPLIED>
<!ATTLIST player castle CDATA #IMPLIED>
<!ATTLIST player sex CDATA #IMPLIED>
<!ATTLIST player agathionId CDATA #IMPLIED>
<!ATTLIST player active_effect_id CDATA #IMPLIED>
<!ELEMENT player EMPTY>

<!ATTLIST target aggro (true|false) #IMPLIED>
<!ATTLIST target siegezone CDATA #IMPLIED>
<!ATTLIST target level CDATA #IMPLIED>
<!ATTLIST target class_id_restriction CDATA #IMPLIED>
<!ATTLIST target active_effect_id CDATA #IMPLIED>
<!ATTLIST target active_skill_id CDATA #IMPLIED>
<!ATTLIST target mindistance CDATA #IMPLIED>
<!ATTLIST target race_id CDATA #IMPLIED>
<!ATTLIST target undead (true|false) #IMPLIED>
<!ATTLIST target using CDATA #IMPLIED>
<!ATTLIST target npcId CDATA #IMPLIED>
<!ELEMENT target EMPTY>

<!ATTLIST using kind CDATA #IMPLIED>
<!ATTLIST using skill CDATA #IMPLIED>
<!ATTLIST using slotitem CDATA #IMPLIED>
<!ATTLIST using weaponChange (true|false) #IMPLIED>
<!ELEMENT using EMPTY>

<!ATTLIST game night (true|false) #IMPLIED>
<!ATTLIST game chance CDATA #IMPLIED>
<!ELEMENT game EMPTY>

=== FearPingWin/L2CraciaFinal/L2_DataPack_CT1.5/data/stats/skills/0800-0899.xml
<?xml version='1.0' encoding='utf-8'?>
<!DOCTYPE list SYSTEM "skills.dtd">
<list>
<skill id="800" levels="3" name="Master Ability - Magic Defense">
  <set name="target" val="TARGET_SELF"/>
  <set name="skillType" val="BUFF"/>
  <set name="operateType" val="OP_PASSIVE"/>
  <set name="castRange" val="-1"/>
  <for>
	<mul order="0x30" val="1.17" stat="mDef"/>
  </for>
</skill>
<skill id="801" levels="1" name="Warrior Ability - Boost CP">
  <set name="target" val="TARGET_SELF"/>
  <set name="skillType" val="BUFF"/>
  <set name="operateType" val="OP_PASSIVE"/>
  <set name="castRange" val="-1"/>
  <for>
	<mul order="0x30" val="1.13" stat="maxCp"/> <!-- Maybe need little correction -->
  </for>
</skill>
<skill id="802" levels="1" name="Wizard Ability - Anti-magic">
  <set name="target" val="TARGET_NONE"/>
  <set name="skillType" val="NOTDONE"/>
  <set name="operateType" val="OP_PASSIVE"/>
  <set name="castRange" val="-1"/>
  <for>
  </for>
</skill>
<skill id="803" levels="1" name="Healer Ability - Divine Protection">
  <set name="target" val="TARGET_NONE"/>
  <set name="skillType" val="NOTDONE"/>
  <set name="operateType" val="OP_PASSIVE"/>
  <set name="castRange" val="-1"/>
  <for>
  </for>
</skill>
<skill id="804" levels="1" name="Knight Ability - Resist Critical">
  <set name="target" val="TARGET_NONE"/>
  <set name="skillType" val="NOTDONE"/>
  <set name="operateType" val="OP_PASSIVE"/>
  <set name="castRange" val="-1"/>
  <for>
  </for>
</skill>
<skill id="805" levels="1" name="not used">
  <set name="target" val="TARGET_NONE"/>
  <set name="skillType" val="NOTDONE"/>
  <set name="operateType" val="OP_PASSIVE"/>
  <set name="castRange" val="-1"/>
  <for>
  </for>
</skill>
<skill id="806" levels="1" name="Magic Obstacle">
  <set name="target" val="TARGET_NONE"/>
  <set name="skillType" val="NOTDONE"/>
  <set name="operateType" val="OP_PASSIVE"/>
  <set name="castRange" val="-1"/>
  <for>
  </for>
</skill>
<skill id="807" levels="1" name="Over-hit">
  <set name="target" val="TARGET_NONE"/>
  <set name="skillType" val="NOTDONE"/>
  <set name="operateType" val="OP_PASSIVE"/>
  <set name="castRange" val="-1"/>
  <for>
  </for>
</skill>
<skill id="808" levels="1" name="Golem Punch">
  <set name="target" val="TARGET_NONE"/>
  <set name="skillType" val="NOTDONE"/>
  <set name="operateType" val="OP_PASSIVE"/>
  <set name="castRange" val="-1"/>
  <for>
  </for>
</skill>
<skill id="809" levels="1" name="Golem Tornado Swing">
  <set name="target" val="TARGET_NONE"/>
  <set name="skillType" val="NOTDONE"/>
  <set name="operateType" val="OP_PASSIVE"/>
  <set name="castRange" val="-1"/>
  <for>
  </for>
</skill>
</list>

=== FearPingWin/L2CraciaFinal/L2_DataPack_c5/data/stats/skills/7000-7099.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE list SYSTEM "skills.dtd">
<list>
<skill id="7001" levels="1" name="Dispel Buff">
<!--Done by KID-->
  <set name="mpConsume" val="96"/>
  <set name="power" val="0.0"/>
  <set name="target" val="TARGET_ONE"/>
  <set name="hitTime" val="6000"/>
  <set name="reuseDelay" val="300000"/>
  <set name="skillTime" val="6000"/>
  <set name="skillType" val="CANCEL"/>
  <set name="isMagic" val="true"/>
  <set name="operateType" val="OP_ACTIVE"/>
  <set name="castRange" val="600"/>
  <set name="effectRange" val="900"/>
  <set name="negateStats" val="BUFF"/>
  <set name="negatePower" val="17.0"/>
</skill>

<skill id="7002" levels="1" name="Dispel Debuff">
<!--Done by KID-->
  <set name="mpConsume" val="154"/>
  <set name="power" val="0.0"/>
  <set name="target" val="TARGET_ONE"/>
  <set name="hitTime" val="6000"/>
  <set name="reuseDelay" val="300000"/>
  <set name="skillTime" val="6000"/>
  <set name="skillType" val="CANCEL"/>
  <set name="isMagic" val="true"/>
  <set name="operateType" val="OP_ACTIVE"/>
  <set name="castRange" val="600"/>
  <set name="effectRange" val="900"/>
  <set name="negateStats" val="STUN SLEEP MUTE FEAR CONFUSION POISON BLEED DEBUFF WEAKNESS PARALYZE"/>
  <set name="negatePower" val="17.0"/>
</skill>

<skill id="7003" levels="1" name="Dispel All">
<!--Done by KID-->
  <set name="mpConsume" val="74"/>
  <set name="power" val="0.0"/>
  <set name="target" val="TARGET_ONE"/>
  <set name="hitTime" val="6000"/>
  <set name="reuseDelay" val="300000"/>
  <set name="skillTime" val="6000"/>
  <set name="skillType" val="CANCEL"/>
  <set name="isMagic" val="true"/>
  <set name="operateType" val="OP_ACTIVE"/>
  <set name="castRange" val="600"/>
  <set name="effectRange" val="900"/>
  <set name="negateStats" val="STUN SLEEP MUTE FEAR CONFUSION POISON BLEED BUFF DEBUFF WEAKNESS PARALYZE"/>
  <set name="negatePower" val="9.0"/>
</skill>

<skill id="7004" levels="2" name="Disple Petrification">
<!-- TODO -->
  <set name="power" val="0.0"/>
  <set name="target" val="TARGET_SELF"/>
  <set name="skillType" val="PASSIVE"/>
  <set name="operateType" val="OP_PASSIVE"/>
  <set name="isMagic" val="true"/>
  <set name="castRange" val="-1"/>
  <set name="effectRange" val="-1"/>
  <for>
  </for>
</skill>
<skill id="7005" levels="4" name="Greater Chant of Vampire">
<!--Done by KID-->
<table name="#mpConsume"> 154 213 244 272 </table>
<table name="#power"> 1.0 2.0 3.0 7.0 </table>
<table name="#abs"> 15 20 25 70 </table>
  <set name="mpConsume" val="#mpConsume"/>
  <set name="power" val="#power"/>
  <set name="target" val="TARGET_PARTY"/>
  <set name="skillRadius" val="900"/>
  <set name="hitTime" val="2000"/>
  <set name="reuseDelay" val="20000"/>
  <set name="skillTime" val="2000"/>
  <set name="skillType" val="BUFF"/>
  <set name="isMagic" val="true"/>
  <set name="operateType" val="OP_ACTIVE"/>
  <set name="buffDuration" val="1200000"/>
  <set name="castRange" val="-1"/>
  <set name="effectRange" val="-1"/>
  <for>
	<effect count="1" name="Buff" time="1200" val="0" stackOrder="#power" stackType="vampire">
		<add order="0x40" stat="absorbDam" val="#abs"/>
	</effect>
  </for>
</skill>
<skill id="7006" levels="13" name="Pa'agrio's Love">
<!--Done by KID-->
<!--lvl 1-12 dupe-->
  <table name="#hot"> 0 0 0 0 0 0 0 0 0 0 0 0 119 </table>
  <table name="#mpConsume"> 0 0 0 0 0 0 0 0 0 0 0 0 239 </table>
  <set name="mpConsume" val="#mpConsume"/>
  <set name="power" val="6.0"/>
  <set name="target" val="TARGET_ALLY"/>
  <set name="skillRadius" val="1500"/>
  <set name="hitTime" val="2000"/>
  <set name="reuseDelay" val="20000"/>
  <set name="skillTime" val="2000"/>
  <set name="skillType" val="HOT"/>
  <set name="isMagic" val="true"/>
  <set name="operateType" val="OP_ACTIVE"/>
  <set name="buffDuration" val="15000"/>
  <set name="castRange" val="-1"/>
  <set name="effectRange" val="-1"/>
  <for>
   <effect count="6" name="HealOverTime" time="5" val="#hot" stackOrder="#hot" stackType="HpRecoverCast"/>
  </for>
</skill>
<skill id="7007" levels="4" name="Greater Seal of Flame">
<!--Done by KID-->
  <table name="#dmg"> 77 94 111 178 </table>
  <table name="#mpConsume"> 97 115 142 153 </table>
  <table name="#power"> 5.0 6.0 7.0 12.0 </table>
  <set name="mpConsume" val="#mpConsume"/>
  <set name="save" val="2"/>
  <set name="power" val="#power"/>
  <set name="target" val="TARGET_AREA"/>
  <set name="skillRadius" val="500"/>
  <set name="hitTime" val="4000"/>
  <set name="element" val="2"/>
  <set name="reuseDelay" val="20000"/>
  <set name="skillTime" val="4000"/>
  <set name="skillType" val="DOT"/>
  <set name="isMagic" val="true"/>
  <set name="operateType" val="OP_ACTIVE"/>
  <set name="buffDuration" val="15000"/>
  <set name="castRange" val="-1"/>
  <set name="effectRange" val="-1"/>
<for>
   <effect count="15" name="DamOverTime" time="1" val="#dmg"/>
</for>
</skill>
<skill id="7029" levels="4" name="Super Haste">
  <set name="power" val="0.0"/>
  <set name="target" val="TARGET_SELF"/>
  <set name="skillType" val="CONT"/>
  <set name="operateType" val="OP_TOGGLE"/>
  <set name="castRange" val="-1"/>
  <set name="effectRange" val="-1"/>
  <table name="#mpConsumeRate"> 1.0 1.0 5.0 0.1 </table>
  <table name="#runSpd"> 2 3 4 5 </table>
  <table name="#pAtk"> 1 1 1 50 </table>
  <table name="#mAtkSpd"> 2 3 5 5 </table>
  <table name="#pAtkSpd"> 1000 1100 1200 1301 </table>
  <table name="#mReuse"> 1 2 3 3 </table>
  <for>
   <effect name="Buff" time="9999998" count="1" val="0">
    <mul order='0x50' stat='runSpd' val="#runSpd"/>
    <mul order='0x50' stat='pAtk' val="#pAtk"/>
    <mul order='0x50' stat='mAtkSpd' val="#mAtkSpd"/>
    <set order='0x50' stat='pAtkSpd' val="#pAtkSpd"/>
    <mul order='0x50' stat='mpConsumeRate' val="#mpConsumeRate"/>
    <div order='0x50' stat='mReuse' val="#mReuse"/>
   </effect>
  </for>
</skill>

<skill id="7030" levels="1" name="Summon King Bugbear">

<table name="#itemConsumeCount"> 8 </table>
<set name="itemConsumeId" val="1458"/>
<set name="mpConsume" val="3"/>
<set name="power" val="0.0"/>
<set name="target" val="TARGET_SELF"/>
<set name="itemConsumeCount" val="#itemConsumeCount"/>
<set name="hitTime" val="4000"/>
<set name="reuseDelay" val="18600000"/>
<set name="skillTime" val="8000"/>
<set name="skillType" val="SUMMON"/>
<set name="isMagic" val="true"/>
<set name="operateType" val="OP_ACTIVE"/>
<set name="castRange" val="-1"/>
<set name="effectRange" val="-1"/>
<!-- Summon-specific -->
<table name="#npcIds">
150
</table>
<set name="npcId" val="#npcIds" />
<set name="expPenalty" val="0.3" />
<set name="isCubic" val="false" />

<for>

</for>

</skill>
<skill id="7031" levels="1" name="Summon Skeleton Royal Guard">

<table name="#itemConsumeCount"> 8 </table>
<set name="itemConsumeId" val="1458"/>
<set name="mpConsume" val="3"/>
<set name="power" val="0.0"/>
<set name="target" val="TARGET_SELF"/>
<set name="itemConsumeCount" val="#itemConsumeCount"/>
<set name="hitTime" val="4000"/>
<set name="reuseDelay" val="18600000"/>
<set name="skillTime" val="8000"/>
<set name="skillType" val="SUMMON"/>
<set name="isMagic" val="true"/>
<set name="operateType" val="OP_ACTIVE"/>
<set name="castRange" val="-1"/>
<set name="effectRange" val="-1"/>
<!-- Summon-specific -->
<table name="#npcIds">
622
</table>
<set name="npcId" val="#npcIds" />
<set name="expPenalty" val="0.3" />
<set name="isCubic" val="false" />
</skill>

<skill id="7032" levels="1" name="Summon Hunter Gargoyle">
<table name="#itemConsumeCount"> 8 </table>
<set name="itemConsumeId" val="1458"/>
<set name="mpConsume" val="3"/>
<set name="power" val="0.0"/>
<set name="target" val="TARGET_SELF"/>
<set name="itemConsumeCount" val="#itemConsumeCount"/>
<set name="hitTime" val="4000"/>
<set name="reuseDelay" val="18600000"/>
<set name="skillTime" val="8000"/>
<set name="skillType" val="SUMMON"/>
<set name="isMagic" val="true"/>
<set name="operateType" val="OP_ACTIVE"/>
<set name="castRange" val="-1"/>
<set name="effectRange" val="-1"/>
<!-- Summon-specific -->
<table name="#npcIds">
241
</table>
<set name="npcId" val="#npcIds" />
<set name="expPenalty" val="0.3" />
<set name="isCubic" val="false" />
</skill>

<skill id="7033" levels="1" name="ZERO">
<!-- skill ZERO -->
  <set name="target" val="TARGET_SELF"/>
  <set name="skillType" val="CONT"/>
  <set name="operateType" val="OP_TOGGLE"/>
  <set name="castRange" val="-1"/>
  <set name="effectRange" val="-1"/>
  <table name="#zero"> 2147483647 </table>
  <table name="#stat"> 50000 </table>
  <for>
    <effect count="0x7fffffff" name="ManaDamOverTime" time="30" val="0">
      <set order="0x50" stat="pAtk" val="#zero"/>
      <set order="0x50" stat="mAtk" val="#zero"/>
      <set order="0x50" stat="pDef" val="#zero"/>
      <set order="0x50" stat="mDef" val="#zero"/>
      <set order="0x50" stat="rCrit" val="#zero"/>
      <set order="0x50" stat="runSpd" val="800"/>
      <set order="0x50" stat="rEvas" val="#zero"/>
      <set order="0x50" stat="pAtkSpd" val="1300"/>
      <set order="0x50" stat="mAtkSpd" val="1890"/>
      <set order="0x50" stat="accCombat" val="#zero"/>
      <set order="0x50" stat="maxCp" val="#stat"/>
      <set order="0x50" stat="maxMp" val="#stat"/>
      <set order="0x50" stat="maxHp" val="#stat"/>
      <div order="0x50" stat="mpConsumeRate" val="2.0"/>
    </effect>
  </for>
</skill>
</list>

=== FearPingWin/L2CraciaFinal/l2jfree-datapack/data/stats/skills/5600-5699.xml
<?xml version='1.0' encoding='utf-8'?>
<!DOCTYPE list SYSTEM "skills.dtd">
<list>
  <skill id="5600" levels="1" name="Betrayal Mark">
    <set name="target" val="TARGET_NONE" />
    <set name="skillType" val="NOTDONE" />
    <set name="operateType" val="OP_PASSIVE" />
    <set name="castRange" val="-1" />
    <for></for>
  </skill>
  <!-- NPC Short-Range Physical Resistance -->
  <skill id="5601" levels="12"
    name="Short-Range Physical Attack Resistance">
    <set name="target" val="TARGET_NONE" />
    <set name="skillType" val="NOTDONE" />
    <set name="operateType" val="OP_PASSIVE" />
    <set name="castRange" val="-1" />
    <for></for>
  </skill>
  <!-- Sacrifice. A state in which HP cannot be recovered. -->
  <skill id="5602" levels="1" name="Transform Sacrifice">
    <set name="target" val="TARGET_NONE" />
    <set name="skillType" val="NOTDONE" />
    <set name="operateType" val="OP_PASSIVE" />
    <set name="castRange" val="-1" />
    <for></for>
  </skill>
  <!-- A state in which MP consumption of skills is greatly decreased, and the probability of a vital spot jab is increased. -->
  <skill id="5603" levels="1" name="Dagger Mastery">
    <set name="target" val="TARGET_NONE" />
    <set name="skillType" val="NOTDONE" />
    <set name="operateType" val="OP_PASSIVE" />
    <set name="castRange" val="-1" />
    <for></for>
  </skill>
  <!-- A state in which MP consumption of skills is greatly decreased, and the success rate of stun attack is increased. -->
  <skill id="5604" levels="1" name="Blunt Mastery">
    <set name="target" val="TARGET_NONE" />
    <set name="skillType" val="NOTDONE" />
    <set name="operateType" val="OP_PASSIVE" />
    <set name="castRange" val="-1" />
    <for></for>
  </skill>
  <!-- Power of Apella. Increased M. Def., increased critical rate, and decreased critical power. -->
  <skill id="5605" levels="2" name="Power of Apella">
    <set name="target" val="TARGET_NONE" />
    <set name="skillType" val="NOTDONE" />
    <set name="operateType" val="OP_PASSIVE" />
    <set name="castRange" val="-1" />
    <for></for>
  </skill>
  <!-- Power of Apella. Increased Dodge, increased Atk. Spd., and decreased critical power. -->
  <skill id="5607" levels="2" name="Power of Apella">
    <set name="target" val="TARGET_NONE" />
    <set name="skillType" val="NOTDONE" />
    <set name="operateType" val="OP_PASSIVE" />
    <set name="castRange" val="-1" />
    <for></for>
  </skill>
  <!-- Power of Apella. Increased P. Def., increased M. Atk., and decreased Speed. -->
  <skill id="5608" levels="2" name="Power of Apella">
    <set name="target" val="TARGET_NONE" />
    <set name="skillType" val="NOTDONE" />
    <set name="operateType" val="OP_PASSIVE" />
    <set name="castRange" val="-1" />
    <for></for>
  </skill>
  <skill id="5609" levels="1" name="Sound 1">
    <set name="target" val="TARGET_NONE" />
    <set name="skillType" val="NOTDONE" />
    <set name="operateType" val="OP_PASSIVE" />
    <set name="castRange" val="-1" />
    <for></for>
  </skill>
  <skill id="5610" levels="1" name="Sound 2">
    <set name="target" val="TARGET_NONE" />
    <set name="skillType" val="NOTDONE" />
    <set name="operateType" val="OP_PASSIVE" />
    <set name="castRange" val="-1" />
    <for></for>
  </skill>
  <skill id="5611" levels="1" name="Sound 3">
    <set name="target" val="TARGET_NONE" />
    <set name="skillType" val="NOTDONE" />
    <set name="operateType" val="OP_PASSIVE" />
    <set name="castRange" val="-1" />
    <for></for>
  </skill>
  <skill id="5612" levels="1" name="Sound 4">
    <set name="target" val="TARGET_NONE" />
    <set name="skillType" val="NOTDONE" />
    <set name="operateType" val="OP_PASSIVE" />
    <set name="castRange" val="-1" />
    <for></for>
  </skill>
  <!-- Provides the ability to recover HP temporarily by damaging the enemy. Excludes damage caused by skills and long-range attacks. Effect 4. -->
  <skill id="5613" levels="4" name="Vampiric Rage">
    <set name="target" val="TARGET_NONE" />
    <set name="skillType" val="NOTDONE" />
    <set name="operateType" val="OP_PASSIVE" />
    <set name="castRange" val="-1" />
    <for></for>
  </skill>
  <!-- He was one of the Devil's retainers from Asmodae, and Beleth placed him among the people in order to rule Hellbound. Although he took over the power and turned Hellbound into the devil's territory after Beleth disappeared for magic experiments. Beleth does not really care about it. -->
  <skill id="5614" levels="1" name="Raid Boss - Level 87">
    <set name="target" val="TARGET_NONE" />
    <set name="skillType" val="NOTDONE" />
    <set name="operateType" val="OP_PASSIVE" />
    <set name="castRange" val="-1" />
    <for></for>
  </skill>
  <!-- He was created when a large number of elemental spirits that were constrained in the basement of Tower of Naia were transformed after being affected by Beleth's magic and Core Naia. Although it is a monster with an unstable shape and mind, which is  
    <skill id="5615" levels="1" name="Raid Boss - Level 87">
    <set name="target" val="TARGET_NONE" />
    <set name="skillType" val="NOTDONE" />
    <set name="operateType" val="OP_PASSIVE" />
    <set name="castRange" val="-1" />
    <for></for>
    </skill>
    <!-- He was created when a large number of elemental spirits that were constrained in the basement of Tower of Naia were transformed after being affected by Beleth's magic and Core Naia. Although it is a monster with an unstable shape and mind, which is  
    <skill id="5616" levels="1" name="Raid Boss - Level 87">
    <set name="target" val="TARGET_NONE" />
    <set name="skillType" val="NOTDONE" />
    <set name="operateType" val="OP_PASSIVE" />
    <set name="castRange" val="-1" />
    <for></for>
    </skill>
    <!-- He was created when a large number of elemental spirits that were constrained in the basement of Tower of Naia were transformed after being affected by Beleth's magic and Core Naia. Although it is a monster with an unstable shape and mind, which is  
    <skill id="5617" levels="1" name="Raid Boss - Level 87">
    <set name="target" val="TARGET_NONE" />
    <set name="skillType" val="NOTDONE" />
    <set name="operateType" val="OP_PASSIVE" />
    <set name="castRange" val="-1" />
    <for></for>
    </skill>
    <!-- He was created when a large number of elemental spirits that were constrained in the basement of Tower of Naia were transformed after being affected by Beleth's magic and Core Naia. Although it is a monster with an unstable shape and mind, which is  
    <skill id="5618" levels="1" name="Raid Boss - Level 87">
    <set name="target" val="TARGET_NONE" />
    <set name="skillType" val="NOTDONE" />
    <set name="operateType" val="OP_PASSIVE" />
    <set name="castRange" val="-1" />
    <for></for>
    </skill>
    <skill id="5619" levels="1"
    name="Presentation - Super Giant Mutated Animal">
    <set name="target" val="TARGET_NONE" />
    <set name="skillType" val="NOTDONE" />
    <set name="operateType" val="OP_PASSIVE" />
    <set name="castRange" val="-1" />
    <for></for>
    </skill>
    </list>
  -->
