=== FearPingWin/L2CraciaFinal/l2jfree-datapack/data/stats/skills/skills.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!-- Root -->
<!ELEMENT list (skill)*>

<!-- Skill -->
<!ATTLIST skill id CDATA #REQUIRED>
<!ATTLIST skill name CDATA #REQUIRED>
<!ATTLIST skill levels CDATA #REQUIRED>
<!ATTLIST skill enchantLevels1 CDATA #IMPLIED>
<!ATTLIST skill enchantLevels2 CDATA #IMPLIED>
<!ATTLIST skill enchantLevels3 CDATA #IMPLIED>
<!ATTLIST skill enchantLevels4 CDATA #IMPLIED>
<!ATTLIST skill enchantLevels5 CDATA #IMPLIED>
<!ELEMENT skill ((table|set|enchant1|enchant2|enchant3|enchant4|enchant5)*,cond?,enchant1cond?,enchant2cond?,enchant3cond?,enchant4cond?,enchant5cond?,for?,enchant1for?,enchant2for?,enchant3for?,enchant4for?,enchant5for?)>

<!-- Table -->
<!ATTLIST table name CDATA #REQUIRED>
<!ELEMENT table (#PCDATA)>

<!-- Property -->
<!ATTLIST set      name CDATA #IMPLIED> <!-- overlapping with stats -->
<!ATTLIST enchant1 name CDATA #REQUIRED>
<!ATTLIST enchant2 name CDATA #REQUIRED>
<!ATTLIST enchant3 name CDATA #REQUIRED>
<!ATTLIST enchant4 name CDATA #REQUIRED>
<!ATTLIST enchant5 name CDATA #REQUIRED>
<!ATTLIST set      val CDATA #REQUIRED>
<!ATTLIST enchant1 val CDATA #REQUIRED>
<!ATTLIST enchant2 val CDATA #REQUIRED>
<!ATTLIST enchant3 val CDATA #REQUIRED>
<!ATTLIST enchant4 val CDATA #REQUIRED>
<!ATTLIST enchant5 val CDATA #REQUIRED>
<!-- <!ELEMENT set      EMPTY> --> <!-- overlapping with stats -->
<!ELEMENT enchant1 EMPTY>
<!ELEMENT enchant2 EMPTY>
<!ELEMENT enchant3 EMPTY>
<!ELEMENT enchant4 EMPTY>
<!ELEMENT enchant5 EMPTY>

<!-- Template -->
<!ELEMENT for         (effect*|(set|add|sub|mul|div|basemul)+)> <!-- TODO -->
<!ELEMENT enchant1for (effect*|(set|add|sub|mul|div|basemul)+)> <!-- TODO -->
<!ELEMENT enchant2for (effect*|(set|add|sub|mul|div|basemul)+)> <!-- TODO -->
<!ELEMENT enchant3for (effect*|(set|add|sub|mul|div|basemul)+)> <!-- TODO -->
<!ELEMENT enchant4for (effect*|(set|add|sub|mul|div|basemul)+)> <!-- TODO -->
<!ELEMENT enchant5for (effect*|(set|add|sub|mul|div|basemul)+)> <!-- TODO -->

<!-- Condition -->
<!ATTLIST cond         msg CDATA #IMPLIED>
<!ATTLIST enchant1cond msg CDATA #IMPLIED>
<!ATTLIST enchant2cond msg CDATA #IMPLIED>
<!ATTLIST enchant3cond msg CDATA #IMPLIED>
<!ATTLIST enchant4cond msg CDATA #IMPLIED>
<!ATTLIST enchant5cond msg CDATA #IMPLIED>
<!ATTLIST cond         msgId CDATA #IMPLIED>
<!ATTLIST enchant1cond msgId CDATA #IMPLIED>
<!ATTLIST enchant2cond msgId CDATA #IMPLIED>
<!ATTLIST enchant3cond msgId CDATA #IMPLIED>
<!ATTLIST enchant4cond msgId CDATA #IMPLIED>
<!ATTLIST enchant5cond msgId CDATA #IMPLIED>
<!ELEMENT cond         (and|or|not|player|target|using|game)>
<!ELEMENT enchant1cond (and|or|not|player|target|using|game)>
<!ELEMENT enchant2cond (and|or|not|player|target|using|game)>
<!ELEMENT enchant3cond (and|or|not|player|target|using|game)>
<!ELEMENT enchant4cond (and|or|not|player|target|using|game)>
<!ELEMENT enchant5cond (and|or|not|player|target|using|game)>

<!-- Effect -->
<!ATTLIST effect name CDATA #REQUIRED>
<!ATTLIST effect count CDATA #IMPLIED>
<!ATTLIST effect time CDATA #REQUIRED>
<!ATTLIST effect self (1) #IMPLIED>
<!ATTLIST effect noicon (1) #IMPLIED>
<!ATTLIST effect val CDATA #REQUIRED>
<!ATTLIST effect abnormal (bleeding|poison|redcircle|ice|wind|flame|stun|mute|root|bighead|stealth|earthquake|invul) #IMPLIED>
<!ATTLIST effect stackType CDATA #IMPLIED>
<!ATTLIST effect stackOrder CDATA #IMPLIED>
<!ELEMENT effect (cond?,(set|add|sub|mul|div|basemul)*)> <!-- TODO: cond? -->

<!-- Stat -->
<!ATTLIST set     stat CDATA #IMPLIED> <!-- overlapping with properties -->
<!ATTLIST add     stat CDATA #REQUIRED>
<!ATTLIST sub     stat CDATA #REQUIRED>
<!ATTLIST mul     stat CDATA #REQUIRED>
<!ATTLIST div     stat CDATA #REQUIRED>
<!ATTLIST basemul stat CDATA #REQUIRED>
<!ATTLIST set     order (0x08|0x99) #IMPLIED> <!-- one level to set it before calculations, and another to set if after --> <!-- overlapping with properties -->
<!ATTLIST add     order (0x10|0x40) #REQUIRED> <!-- same level for add/sub -->
<!ATTLIST sub     order (0x10|0x40) #REQUIRED> <!-- same level for add/sub -->
<!ATTLIST mul     order (0x30) #REQUIRED> <!-- same level for mul/div -->
<!ATTLIST div     order (0x30) #REQUIRED> <!-- same level for mul/div -->
<!ATTLIST basemul order (0x30) #REQUIRED> <!-- same level with mul/div -> COULD CAUSE PROBLEMS -> SHOULD BE CHANGED -->
<!ATTLIST set     val CDATA #REQUIRED>
<!ATTLIST add     val CDATA #REQUIRED>
<!ATTLIST sub     val CDATA #REQUIRED>
<!ATTLIST mul     val CDATA #REQUIRED>
<!ATTLIST div     val CDATA #REQUIRED>
<!ATTLIST basemul val CDATA #REQUIRED>
<!ELEMENT set     (and|or|not|player|target|using|game)?> <!-- overlapping with properties -->
<!ELEMENT add     (and|or|not|player|target|using|game)?>
<!ELEMENT sub     (and|or|not|player|target|using|game)?>
<!ELEMENT mul     (and|or|not|player|target|using|game)?>
<!ELEMENT div     (and|or|not|player|target|using|game)?>
<!ELEMENT basemul (and|or|not|player|target|using|game)?>

<!-- Logic -->
<!ELEMENT and ((and|or|not|player|target|using|game)+)> <!-- TODO: make sure <and> tags contains multiple elements -->
<!-- <!ELEMENT and ((and|or|not|player|target|using|game),(and|or|not|player|target|using|game)+)> -->
<!ELEMENT or  ((and|or|not|player|target|using|game),(and|or|not|player|target|using|game)+)>
<!ELEMENT not (and|or|not|player|target|using|game)>

<!-- Conditions -->
<!ATTLIST player skill (true|false) #IMPLIED>
<!ATTLIST player race (Human|Elf|Darkelf|Orc|Dwarf|Kamael) #IMPLIED>
<!ATTLIST player level CDATA #IMPLIED>
<!ATTLIST player resting (true|false) #IMPLIED>
<!ATTLIST player moving (true|false) #IMPLIED>
<!ATTLIST player running (true|false) #IMPLIED>
<!ATTLIST player walking (true|false) #IMPLIED>
<!ATTLIST player behind (true|false) #IMPLIED>
<!ATTLIST player front (true|false) #IMPLIED>
<!ATTLIST player chaotic (true|false) #IMPLIED>
<!ATTLIST player olympiad (true|false) #IMPLIED>
<!ATTLIST player flying (true|false) #IMPLIED>
<!ATTLIST player hp CDATA #IMPLIED>
<!ATTLIST player mp CDATA #IMPLIED>
<!ATTLIST player cp CDATA #IMPLIED>
<!ATTLIST player attack_stance (true|false) #IMPLIED>
<!ATTLIST player grade CDATA #IMPLIED>
<!ATTLIST player siegezone CDATA #IMPLIED>
<!ATTLIST player battle_force (2|3) #IMPLIED>
<!ATTLIST player spell_force (2|3) #IMPLIED>
<!ATTLIST player weight CDATA #IMPLIED>
<!ATTLIST player invSize CDATA #IMPLIED>
<!ATTLIST player pledgeClass CDATA #IMPLIED>
<!ATTLIST player clanHall CDATA #IMPLIED>
<!ATTLIST player fort CDATA #IMPLIED>
<!ATTLIST player castle CDATA #IMPLIED>
<!ATTLIST player sex CDATA #IMPLIED>
<!ATTLIST player agathionId CDATA #IMPLIED>
<!ATTLIST player active_effect_id CDATA #IMPLIED>
<!ELEMENT player EMPTY>

<!ATTLIST target aggro (true|false) #IMPLIED>
<!ATTLIST target siegezone CDATA #IMPLIED>
<!ATTLIST target level CDATA #IMPLIED>
<!ATTLIST target class_id_restriction CDATA #IMPLIED>
<!ATTLIST target active_effect_id CDATA #IMPLIED>
<!ATTLIST target active_skill_id CDATA #IMPLIED>
<!ATTLIST target mindistance CDATA #IMPLIED>
<!ATTLIST target race_id CDATA #IMPLIED>
<!ATTLIST target undead (true|false) #IMPLIED>
<!ATTLIST target using CDATA #IMPLIED>
<!ATTLIST target npcId CDATA #IMPLIED>
<!ELEMENT target EMPTY>

<!ATTLIST using kind CDATA #IMPLIED>
<!ATTLIST using skill CDATA #IMPLIED>
<!ATTLIST using slotitem CDATA #IMPLIED>
<!ATTLIST using weaponChange (true|false) #IMPLIED>
<!ELEMENT using EMPTY>

<!ATTLIST game night (true|false) #IMPLIED>
<!ATTLIST game chance CDATA #IMPLIED>
<!ELEMENT game EMPTY>

=== FearPingWin/L2CraciaFinal/l2jfree-datapack/data/stats/skills/21000-21099.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE list SYSTEM "skills.dtd">
<list>
  <skill id="21000" levels="1" name="Release Seal on Agathion - Majo">
    <set name="target" val="TARGET_SELF" />
    <set name="skillType" val="AGATHION" />
    <set name="hitTime" val="3000" />
    <set name="staticHitTime" val="true" />
    <set name="operateType" val="OP_ACTIVE" />
    <set name="npcId" val="1501" />
    <set name="castRange" val="-1" />
    <set name="effectRange" val="-1" />
  </skill>
  <skill id="21001" levels="1" name="Release Seal on Agathion - Gold Majo">
    <set name="target" val="TARGET_SELF" />
    <set name="skillType" val="AGATHION" />
    <set name="hitTime" val="3000" />
    <set name="staticHitTime" val="true" />
    <set name="operateType" val="OP_ACTIVE" />
    <set name="npcId" val="1502" />
    <set name="castRange" val="-1" />
    <set name="effectRange" val="-1" />
  </skill>
  <skill id="21002" levels="1" name="Release Seal on Agathion - Black Majo">
    <set name="target" val="TARGET_SELF" />
    <set name="skillType" val="AGATHION" />
    <set name="hitTime" val="3000" />
    <set name="staticHitTime" val="true" />
    <set name="operateType" val="OP_ACTIVE" />
    <set name="npcId" val="1503" />
    <set name="castRange" val="-1" />
    <set name="effectRange" val="-1" />
  </skill>
  <skill id="21003" levels="1" name="Release Seal on Agathion - Plaipitak">
    <set name="target" val="TARGET_SELF" />
    <set name="skillType" val="AGATHION" />
    <set name="hitTime" val="3000" />
    <set name="staticHitTime" val="true" />
    <set name="operateType" val="OP_ACTIVE" />
    <set name="npcId" val="1504" />
    <set name="castRange" val="-1" />
    <set name="effectRange" val="-1" />
  </skill>
  <skill id="21004" levels="1" name="Wind Walk">
    <set name="target" val="TARGET_NONE" />
    <set name="skillType" val="NOTDONE" />
    <set name="operateType" val="OP_PASSIVE" />
    <set name="castRange" val="-1" />
  </skill>
  <skill id="21005" levels="3" name="Agility">
    <set name="target" val="TARGET_NONE" />
    <set name="skillType" val="NOTDONE" />
    <set name="operateType" val="OP_PASSIVE" />
    <set name="castRange" val="-1" />
  </skill>
  <skill id="21006" levels="1" name="Large Firework Effect">
    <set name="target" val="TARGET_NONE" />
    <set name="skillType" val="NOTDONE" />
    <set name="operateType" val="OP_PASSIVE" />
    <set name="castRange" val="-1" />
  </skill>
  <skill id="21007" levels="1" name="Ability of Doubt">
    <set name="target" val="TARGET_NONE" />
    <set name="skillType" val="NOTDONE" />
    <set name="operateType" val="OP_PASSIVE" />
    <set name="castRange" val="-1" />
  </skill>
  <skill id="21008" levels="1" name="Release Seal on Agathion - Baby Panda">
    <set name="target" val="TARGET_NONE" />
    <set name="skillType" val="NOTDONE" />
    <set name="operateType" val="OP_PASSIVE" />
    <set name="castRange" val="-1" />
  </skill>
  <skill id="21009" levels="1" name="Release Seal on Agathion - Bamboo Panda">
    <set name="target" val="TARGET_NONE" />
    <set name="skillType" val="NOTDONE" />
    <set name="operateType" val="OP_PASSIVE" />
    <set name="castRange" val="-1" />
  </skill>
  <skill id="21010" levels="1" name="Release Seal on Agathion - Sexy Panda">
    <set name="target" val="TARGET_NONE" />
    <set name="skillType" val="NOTDONE" />
    <set name="operateType" val="OP_PASSIVE" />
    <set name="castRange" val="-1" />
  </skill>
  <skill id="21011" levels="1" name="Energy Recovery">
    <set name="target" val="TARGET_NONE" />
    <set name="skillType" val="NOTDONE" />
    <set name="operateType" val="OP_PASSIVE" />
    <set name="castRange" val="-1" />
  </skill>
  <skill id="21012" levels="1" name="Energy Recovery">
    <set name="target" val="TARGET_NONE" />
    <set name="skillType" val="NOTDONE" />
    <set name="operateType" val="OP_PASSIVE" />
    <set name="castRange" val="-1" />
  </skill>
  <skill id="21013" levels="1" name="Energy Recovery">
    <set name="target" val="TARGET_NONE" />
    <set name="skillType" val="NOTDONE" />
    <set name="operateType" val="OP_PASSIVE" />
    <set name="castRange" val="-1" />
  </skill>
  <skill id="21014" levels="1" name="Scissors">
    <set name="target" val="TARGET_NONE" />
    <set name="skillType" val="NOTDONE" />
    <set name="operateType" val="OP_PASSIVE" />
    <set name="castRange" val="-1" />
  </skill>
  <skill id="21015" levels="1" name="Rock">
    <set name="target" val="TARGET_NONE" />
    <set name="skillType" val="NOTDONE" />
    <set name="operateType" val="OP_PASSIVE" />
    <set name="castRange" val="-1" />
  </skill>
  <skill id="21016" levels="1" name="Paper">
    <set name="target" val="TARGET_NONE" />
    <set name="skillType" val="NOTDONE" />
    <set name="operateType" val="OP_PASSIVE" />
    <set name="castRange" val="-1" />
  </skill>
  <skill id="21017" levels="1" name="Holiday Dream Weapon">
    <set name="target" val="TARGET_NONE" />
    <set name="skillType" val="NOTDONE" />
    <set name="operateType" val="OP_PASSIVE" />
    <set name="castRange" val="-1" />
  </skill>
  <skill id="21018" levels="1" name="Holiday Dream Weapon">
    <set name="target" val="TARGET_NONE" />
    <set name="skillType" val="NOTDONE" />
    <set name="operateType" val="OP_PASSIVE" />
    <set name="castRange" val="-1" />
  </skill>
  <skill id="21019" levels="1" name="Holiday Dream Weapon">
    <set name="target" val="TARGET_NONE" />
    <set name="skillType" val="NOTDONE" />
    <set name="operateType" val="OP_PASSIVE" />
    <set name="castRange" val="-1" />
  </skill>
  <skill id="21020" levels="1" name="Holiday Dream Weapon">
    <set name="target" val="TARGET_NONE" />
    <set name="skillType" val="NOTDONE" />
    <set name="operateType" val="OP_PASSIVE" />
    <set name="castRange" val="-1" />
  </skill>
  <skill id="21021" levels="1" name="Holiday Dream Weapon">
    <set name="target" val="TARGET_NONE" />
    <set name="skillType" val="NOTDONE" />
    <set name="operateType" val="OP_PASSIVE" />
    <set name="castRange" val="-1" />
  </skill>
  <skill id="21022" levels="1" name="Holiday Dream Weapon">
    <set name="target" val="TARGET_NONE" />
    <set name="skillType" val="NOTDONE" />
    <set name="operateType" val="OP_PASSIVE" />
    <set name="castRange" val="-1" />
  </skill>
  <skill id="21023" levels="1" name="Holiday Dream Weapon">
    <set name="target" val="TARGET_NONE" />
    <set name="skillType" val="NOTDONE" />
    <set name="operateType" val="OP_PASSIVE" />
    <set name="castRange" val="-1" />
  </skill>
  <skill id="21024" levels="1" name="Holiday Dream Weapon">
    <set name="target" val="TARGET_NONE" />
    <set name="skillType" val="NOTDONE" />
    <set name="operateType" val="OP_PASSIVE" />
    <set name="castRange" val="-1" />
  </skill>
  <skill id="21025" levels="1" name="Holiday Dream Weapon">
    <set name="target" val="TARGET_NONE" />
    <set name="skillType" val="NOTDONE" />
    <set name="operateType" val="OP_PASSIVE" />
    <set name="castRange" val="-1" />
  </skill>
  <skill id="21026" levels="1" name="Holiday Dream Weapon">
    <set name="target" val="TARGET_NONE" />
    <set name="skillType" val="NOTDONE" />
    <set name="operateType" val="OP_PASSIVE" />
    <set name="castRange" val="-1" />
  </skill>
  <skill id="21027" levels="1" name="Holiday Dream Weapon">
    <set name="target" val="TARGET_NONE" />
    <set name="skillType" val="NOTDONE" />
    <set name="operateType" val="OP_PASSIVE" />
    <set name="castRange" val="-1" />
  </skill>
  <skill id="21028" levels="1" name="Holiday Dream Weapon">
    <set name="target" val="TARGET_NONE" />
    <set name="skillType" val="NOTDONE" />
    <set name="operateType" val="OP_PASSIVE" />
    <set name="castRange" val="-1" />
  </skill>
  <skill id="21029" levels="1" name="Holiday Dream Weapon">
    <set name="target" val="TARGET_NONE" />
    <set name="skillType" val="NOTDONE" />
    <set name="operateType" val="OP_PASSIVE" />
    <set name="castRange" val="-1" />
  </skill>
  <skill id="21030" levels="1" name="Holiday Dream Weapon">
    <set name="target" val="TARGET_NONE" />
    <set name="skillType" val="NOTDONE" />
    <set name="operateType" val="OP_PASSIVE" />
    <set name="castRange" val="-1" />
  </skill>
</list>

=== FearPingWin/L2CraciaFinal/L2_DataPack_IL/data/stats/skills/2300-2399.xml
<?xml version='1.0' encoding='utf-8'?>
<!DOCTYPE list SYSTEM "skills.dtd">
<list>
<skill id="2300" levels="1" name="Hair Style Change Potion">
  <set name="target" val="TARGET_NONE"/>
  <set name="skillType" val="NOTDONE"/>
  <set name="operateType" val="OP_ACTIVE"/>
  <set name="castRange" val="-1"/>
  <for>
  </for>
</skill>
<skill id="2301" levels="1" name="Hair Style Change Potion">
  <set name="target" val="TARGET_NONE"/>
  <set name="skillType" val="NOTDONE"/>
  <set name="operateType" val="OP_ACTIVE"/>
  <set name="castRange" val="-1"/>
  <for>
  </for>
</skill>
<skill id="2302" levels="1" name="Hair Style Change Potion">
  <set name="target" val="TARGET_NONE"/>
  <set name="skillType" val="NOTDONE"/>
  <set name="operateType" val="OP_ACTIVE"/>
  <set name="castRange" val="-1"/>
  <for>
  </for>
</skill>
<skill id="2303" levels="1" name="Hair Style Change Potion">
  <set name="target" val="TARGET_NONE"/>
  <set name="skillType" val="NOTDONE"/>
  <set name="operateType" val="OP_ACTIVE"/>
  <set name="castRange" val="-1"/>
  <for>
  </for>
</skill>
<skill id="2304" levels="1" name="Hair Style Change Potion">
  <set name="target" val="TARGET_NONE"/>
  <set name="skillType" val="NOTDONE"/>
  <set name="operateType" val="OP_ACTIVE"/>
  <set name="castRange" val="-1"/>
  <for>
  </for>
</skill>
<skill id="2305" levels="1" name="Primeval Potion">
<!--
  Needs to be finished.
  Target is set to TARGET_NONE, skillType to NOTDONE for server compatability.
  Description(s):
      Improves resistance to various poisons and anesthetics that originate on the Primeval Isle.
-->
  <set name="target" val="TARGET_NONE"/>
  <set name="skillType" val="NOTDONE"/>
  <set name="operateType" val="OP_PASSIVE"/>
  <set name="castRange" val="-1"/>
  <for>
  </for>
</skill>
<skill id="2306" levels="3" name="Primeval Crystals">
<!--
  Needs to be finished.
  Target is set to TARGET_NONE, skillType to NOTDONE for server compatability.
  Description(s):
      Lvl 1 Name - Blue Primeval Crystal
	  Lvl 2 Name - Green Primeval Crystal
	  Lvl 3 Name - Red Primeval Crystal
-->
  <set name="target" val="TARGET_NONE"/>
  <set name="skillType" val="NOTDONE"/>
  <set name="operateType" val="OP_PASSIVE"/>
  <set name="castRange" val="-1"/>
  <for>
  </for>
</skill>
<skill id="2307" levels="1" name="Remove Petrification Scroll">
<!--
  Needs to be finished.
  Target is set to TARGET_NONE, skillType to NOTDONE for server compatability.
  Description(s):
      none
-->
  <set name="target" val="TARGET_NONE"/>
  <set name="skillType" val="NOTDONE"/>
  <set name="operateType" val="OP_PASSIVE"/>
  <set name="castRange" val="-1"/>
  <for>
  </for>
</skill>
<skill id="2308" levels="36" name="Event Item">
<!--
  Needs to be finished.
  Target is set to TARGET_NONE, skillType to NOTDONE for server compatability.
  Description(s):
      Lvl 1-36 Name - Event Item
-->
  <set name="target" val="TARGET_NONE"/>
  <set name="skillType" val="NOTDONE"/>
  <set name="operateType" val="OP_PASSIVE"/>
  <set name="castRange" val="-1"/>
  <for>
  </for>
</skill>
<skill id="2309" levels="1" name="Pig Chest">
<!--
  Needs to be finished.
  Target is set to TARGET_NONE, skillType to NOTDONE for server compatability.
  Description(s):
      Lvl 1 - none
-->
  <set name="target" val="TARGET_NONE"/>
  <set name="skillType" val="NOTDONE"/>
  <set name="operateType" val="OP_PASSIVE"/>
  <set name="castRange" val="-1"/>
  <for>
  </for>
</skill>
<skill id="2310" levels="1" name="Scroll of Guidance - Event Use">
<!--
  Needs to be finished.
  Target is set to TARGET_NONE, skillType to NOTDONE for server compatability.
  Description(s):
      Lvl 1 - Increases Accuracy. Effect 3.
-->
  <set name="target" val="TARGET_NONE"/>
  <set name="skillType" val="NOTDONE"/>
  <set name="operateType" val="OP_PASSIVE"/>
  <set name="castRange" val="-1"/>
  <for>
  </for>
</skill>
<skill id="2311" levels="1" name="Scroll of Death Whisper - Event Use">
<!--
  Needs to be finished.
  Target is set to TARGET_NONE, skillType to NOTDONE for server compatability.
  Description(s):
      Lvl 1 - Increases critical attack power. Effect 3.
-->
  <set name="target" val="TARGET_NONE"/>
  <set name="skillType" val="NOTDONE"/>
  <set name="operateType" val="OP_PASSIVE"/>
  <set name="castRange" val="-1"/>
  <for>
  </for>
</skill>
<skill id="2312" levels="1" name="Scroll of Focus - Event Use">
<!--
  Needs to be finished.
  Target is set to TARGET_NONE, skillType to NOTDONE for server compatability.
  Description(s):
      Lvl 1 - Increases critical attack rate. Effect 3.
-->
  <set name="target" val="TARGET_NONE"/>
  <set name="skillType" val="NOTDONE"/>
  <set name="operateType" val="OP_PASSIVE"/>
  <set name="castRange" val="-1"/>
  <for>
  </for>
</skill>
<skill id="2313" levels="1" name="Scroll of Acumen - Event Use">
<!--
  Needs to be finished.
  Target is set to TARGET_NONE, skillType to NOTDONE for server compatability.
  Description(s):
      Lvl 1 - Increases Casting Spd. Effect 3.
-->
  <set name="target" val="TARGET_NONE"/>
  <set name="skillType" val="NOTDONE"/>
  <set name="operateType" val="OP_PASSIVE"/>
  <set name="castRange" val="-1"/>
  <for>
  </for>
</skill>
<skill id="2314" levels="1" name="Scroll of Haste - Event Use">
<!--
  Needs to be finished.
  Target is set to TARGET_NONE, skillType to NOTDONE for server compatability.
  Description(s):
      Lvl 1 - Increases Atk. Spd. Effect 2.
-->
  <set name="target" val="TARGET_NONE"/>
  <set name="skillType" val="NOTDONE"/>
  <set name="operateType" val="OP_PASSIVE"/>
  <set name="castRange" val="-1"/>
  <for>
  </for>
</skill>
<skill id="2315" levels="1" name="Scroll of Agility - Event Use">
<!--
  Needs to be finished.
  Target is set to TARGET_NONE, skillType to NOTDONE for server compatability.
  Description(s):
      Lvl 1 - Increases Evasion. Effect 3.
-->
  <set name="target" val="TARGET_NONE"/>
  <set name="skillType" val="NOTDONE"/>
  <set name="operateType" val="OP_PASSIVE"/>
  <set name="castRange" val="-1"/>
  <for>
  </for>
</skill>
<skill id="2316" levels="1" name="Scroll of Empower - Event Use">
<!--
  Needs to be finished.
  Target is set to TARGET_NONE, skillType to NOTDONE for server compatability.
  Description(s):
      Lvl 1 - Increases M. Atk. Effect 3.
-->
  <set name="target" val="TARGET_NONE"/>
  <set name="skillType" val="NOTDONE"/>
  <set name="operateType" val="OP_PASSIVE"/>
  <set name="castRange" val="-1"/>
  <for>
  </for>
</skill>
<skill id="2317" levels="1" name="Scroll of Might - Event Use">
<!--
  Needs to be finished.
  Target is set to TARGET_NONE, skillType to NOTDONE for server compatability.
  Description(s):
      Lvl 1 - Increases P. Atk. Effect 3.
-->
  <set name="target" val="TARGET_NONE"/>
  <set name="skillType" val="NOTDONE"/>
  <set name="operateType" val="OP_PASSIVE"/>
  <set name="castRange" val="-1"/>
  <for>
  </for>
</skill>
<skill id="2318" levels="1" name="Scroll of Wind Walk - Event Use">
<!--
  Needs to be finished.
  Target is set to TARGET_NONE, skillType to NOTDONE for server compatability.
  Description(s):
      Lvl 1 - Increases Speed. Effect 2.
-->
  <set name="target" val="TARGET_NONE"/>
  <set name="skillType" val="NOTDONE"/>
  <set name="operateType" val="OP_PASSIVE"/>
  <set name="castRange" val="-1"/>
  <for>
  </for>
</skill>
<skill id="2319" levels="1" name="Scroll of Shield - Event Use">
<!--
  Needs to be finished.
  Target is set to TARGET_NONE, skillType to NOTDONE for server compatability.
  Description(s):
      Lvl 1 - Increases P. Def. Effect 3.
-->
  <set name="target" val="TARGET_NONE"/>
  <set name="skillType" val="NOTDONE"/>
  <set name="operateType" val="OP_PASSIVE"/>
  <set name="castRange" val="-1"/>
  <for>
  </for>
</skill>
<skill id="2320" levels="1" name="Blessed Scroll of Escape - Event Use">
<!--
  Needs to be finished.
  Target is set to TARGET_NONE, skillType to NOTDONE for server compatability.
  Description(s):
      Lvl 1 - none
-->
  <set name="target" val="TARGET_NONE"/>
  <set name="skillType" val="NOTDONE"/>
  <set name="operateType" val="OP_PASSIVE"/>
  <set name="castRange" val="-1"/>
  <for>
  </for>
</skill>
<skill id="2321" levels="1" name="Blessed Scroll of Resurrection - Event Use">
<!--
  Needs to be finished.
  Target is set to TARGET_NONE, skillType to NOTDONE for server compatability.
  Description(s):
      Lvl 1 - none
-->
  <set name="target" val="TARGET_NONE"/>
  <set name="skillType" val="NOTDONE"/>
  <set name="operateType" val="OP_PASSIVE"/>
  <set name="castRange" val="-1"/>
  <for>
  </for>
</skill>
</list>

=== FearPingWin/L2CraciaFinal/l2jfree-datapack/data/stats/skills/9000-9099.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE list SYSTEM "../../templates/skills.dtd">
<list>
  <skill id="9007" levels="1" name="Custom Mana Drug">
    <!-- Done by DJ MELERIX -->
    <set name="itemConsumeId" val="726"/>
    <set name="itemConsumeCount" val="1"/>
    <set name="isPotion" val="true"/>
    <set name="magicLvl" val="1"/>
    <set name="operateType" val="OP_ACTIVE"/>
    <set name="skillType" val="MPHOT"/>
    <set name="target" val="TARGET_SELF"/>
    <cond msgId="113" addName="1">
      <player flyMounted="False"/>
    </cond>
    <for>
      <effect count="3" name="ManaHealOverTime" time="5" val="1.5" stackOrder="1.5" stackType="mp_recover"/>
    </for>
  </skill>
  <skill id="9008" levels="1" name="Custom Mana Potion">
    <!-- Done by DJ MELERIX -->
    <set name="itemConsumeId" val="728"/>
    <set name="itemConsumeCount" val="1"/>
    <set name="isPotion" val="true"/>
    <set name="magicLvl" val="1"/>
    <set name="operateType" val="OP_ACTIVE"/>
    <set name="power" val="100"/>
    <set name="skillType" val="MANAHEAL"/>
    <set name="target" val="TARGET_SELF"/>
    <cond msgId="113" addName="1">
      <player flyMounted="False"/>
    </cond>
  </skill>
  <skill id="9009" levels="1" name="Grade Penalty - Weapon">
    <!-- Done by savormix, verified by Psycho -->
    <set name="operateType" val="OP_PASSIVE"/>
    <set name="skillType" val="BUFF"/>
    <set name="target" val="TARGET_SELF"/>
    <set name="stayAfterDeath" val="true"/>
    <set name="sendToClient" val="false"/>
    <for>
      <mul order="0x30" stat="pAtkSpd" val="0.9"/>
      <sub order="0x40" stat="accCombat" val="16"/>
    </for>
  </skill>
  <skill id="9010" levels="5" name="Grade Penalty - Armor">
    <!-- Done by savormix, verified by Psycho -->
    <table name="#AtkSpd"> 0.83 0.69 0.58 0.5 0.5 </table>
    <table name="#rEvas"> 2 4 6 8 10 </table>
    <table name="#runSpd"> 0.83 0.75 0.66 0.59 0.59 </table> <!-- Yes, in percentage -->
    <set name="operateType" val="OP_PASSIVE"/>
    <set name="skillType" val="BUFF"/>
    <set name="target" val="TARGET_SELF"/>
    <set name="stayAfterDeath" val="true"/>
    <set name="sendToClient" val="false"/>
    <for>
      <mul order="0x30" stat="pAtkSpd" val="#AtkSpd">
        <using kind="Sword,Blunt,Dagger,Bow,Pole,Etc,Fist,Dual Sword,Dual Fist,Big Sword,Big Blunt,Ancient,Crossbow,Rapier,Dual Dagger"/>
      </mul>
      <sub order="0x40" stat="rEvas" val="#rEvas"/>
      <mul order="0x30" stat="runSpd" val="#runSpd"/>
      <mul order="0x30" stat="mAtkSpd" val="#AtkSpd"/>
    </for>
  </skill>
</list>
