=== FearPingWin/L2CraciaFinal/l2jfree-datapack/data/templates/instances.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!-- Root -->
<!ATTLIST instance name CDATA #REQUIRED>
<!ELEMENT instance (activityTime?,timeDelay?,allowSummon?,emptyDestroyTime?,PvPInstance?,returnteleport?,doorlist?,spawnlist?,spawnPoint?)>

<!-- Activity Time (minutes) -->
<!ATTLIST activityTime val CDATA #REQUIRED>
<!ELEMENT activityTime EMPTY>

<!-- Time Delay (hours), NOT SUPPORTED AT THIS TIME -->
<!ATTLIST timeDelay val CDATA #REQUIRED>
<!ELEMENT timeDelay EMPTY>

<!-- Allow Summon [Friend type skills] -->
<!ATTLIST allowSummon val (true|false) #REQUIRED>
<!ELEMENT allowSummon EMPTY>

<!-- Instance inactive removal time (seconds) -->
<!ATTLIST emptyDestroyTime val CDATA #IMPLIED>
<!ELEMENT emptyDestroyTime EMPTY>

<!-- Whether pvp is allowed in the instance -->
<!ATTLIST PvPInstance val (true|false) #REQUIRED>
<!ELEMENT PvPInstance EMPTY>

<!-- Return Teleport [location] -->
<!ATTLIST returnteleport x CDATA #REQUIRED>
<!ATTLIST returnteleport y CDATA #REQUIRED>
<!ATTLIST returnteleport z CDATA #REQUIRED>
<!ELEMENT returnteleport EMPTY>

<!-- Door list -->
<!ELEMENT doorlist (door)+>
<!ATTLIST door doorId CDATA #REQUIRED>
<!ATTLIST door open (true|false) #IMPLIED>
<!ELEMENT door EMPTY>

<!-- Spawn list -->
<!ELEMENT spawnlist (spawn)+>
<!ATTLIST spawn npcId CDATA #REQUIRED>
<!ATTLIST spawn x CDATA #REQUIRED>
<!ATTLIST spawn y CDATA #REQUIRED>
<!ATTLIST spawn z CDATA #REQUIRED>
<!ATTLIST spawn heading CDATA #REQUIRED>
<!ATTLIST spawn respawn CDATA #REQUIRED>
<!ATTLIST spawn amount CDATA #REQUIRED>
<!ELEMENT spawn EMPTY>

<!-- Spawn Point -->
<!ATTLIST spawnPoint spawnX CDATA #REQUIRED>
<!ATTLIST spawnPoint spawnY CDATA #REQUIRED>
<!ATTLIST spawnPoint spawnZ CDATA #REQUIRED>
<!ELEMENT spawnPoint EMPTY>

=== FearPingWin/L2CraciaFinal/l2jfree-datapack/data/instances/DarkCloudMansion.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE list SYSTEM "../templates/instances.dtd">
<instance name="Dark Cloud Mansion">
  <activityTime val="30"/>
  <timeDelay val="24"/>
  <allowSummon val="false"/>
  <returnteleport x="139408" y="150805" z="-3108"/>
  <doorlist>
    <door doorId="24230001"/>
    <door doorId="24230002"/>
    <door doorId="24230005"/>
    <door doorId="24230003"/>
    <door doorId="24230004"/>
    <door doorId="24230006"/>
    <door doorId="24230007"/>
    <door doorId="24230008"/>
    <door doorId="24230009"/>
    <door doorId="24230010"/>
    <door doorId="24230011"/>
    <door doorId="24230012"/>
    <door doorId="24230013"/>
  </doorlist>
</instance>

=== FearPingWin/L2CraciaFinal/l2jfree-datapack/data/instances/Kamaloka-23.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE list SYSTEM "../templates/instances.dtd">
<instance name="Kamaloka-23">
  <activityTime val="30"/>
  <timeDelay val="24"/>
  <allowSummon val="false"/>
  <emptyDestroyTime val="300"/>
  <returnteleport x="-13870" y="123767" z="-3117"/>
  <spawnlist>
    <spawn npcId="18554" x="-56255" y="-219879" z="-8117" heading="0" respawn="0" amount="1"/>
  </spawnlist>
</instance>
