=== FearPingWin/L2CraciaFinal/l2jfree-datapack/data/templates/zones.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!-- Root -->
<!ELEMENT list (zone)*>

<!-- Zone -->
<!ATTLIST zone enabled (true|false) #IMPLIED>
<!ATTLIST zone id CDATA #REQUIRED>
<!ATTLIST zone name CDATA #REQUIRED>
<!ATTLIST zone type (Arena|Boss|CastleTeleport|Castle|Clanhall|CoreBarrier|Damage|Danger|DefenderSpawn|Dynamic|Fishing|Fort|HeadQuarters|Jail|Mothertree|Regeneration|SiegeDanger|Siege|Stadium|Town|Water) #IMPLIED>
<!ELEMENT zone (entity?,instance?,msg?,settings?,skill?,restart_chaotic*,restart_owner*,shape+,cond*)>

<!-- Entity -->
<!ATTLIST entity castleId CDATA #IMPLIED>
<!ATTLIST entity clanhallId CDATA #IMPLIED>
<!ATTLIST entity fortId CDATA #IMPLIED>
<!ATTLIST entity townId CDATA #IMPLIED>
<!ELEMENT entity EMPTY>

<!-- Instance -->
<!ATTLIST instance instanceName CDATA #REQUIRED>
<!ATTLIST instance instanceGroup (alliance|clan|party) #REQUIRED>
<!ATTLIST instance minPlayers CDATA #IMPLIED>
<!ATTLIST instance maxPlayers CDATA #IMPLIED>
<!ELEMENT instance EMPTY>

<!-- Messages -->
<!ATTLIST msg onEnter CDATA #IMPLIED>
<!ATTLIST msg onExit CDATA #IMPLIED>
<!ELEMENT msg EMPTY>

<!-- Restarts -->
<!ATTLIST restart_chaotic x CDATA #REQUIRED>
<!ATTLIST restart_chaotic y CDATA #REQUIRED>
<!ATTLIST restart_chaotic z CDATA #REQUIRED>
<!ELEMENT restart_chaotic EMPTY>
<!ATTLIST restart_owner x CDATA #REQUIRED>
<!ATTLIST restart_owner y CDATA #REQUIRED>
<!ATTLIST restart_owner z CDATA #REQUIRED>
<!ELEMENT restart_owner EMPTY>

<!-- Shape -->
<!ATTLIST shape type (Cylinder|ExCylinder|Poly|Rect) #REQUIRED>
<!ATTLIST shape zMin CDATA #REQUIRED>
<!ATTLIST shape zMax CDATA #REQUIRED>
<!ATTLIST shape radius CDATA #IMPLIED>
<!ATTLIST shape innerRadius CDATA #IMPLIED>
<!ATTLIST shape outerRadius CDATA #IMPLIED>
<!ELEMENT shape (point+)>
<!-- Point -->
<!ATTLIST point x CDATA #REQUIRED>
<!ATTLIST point y CDATA #REQUIRED>
<!ELEMENT point EMPTY>

<!-- Skill -->
<!ATTLIST skill applyEnter CDATA #IMPLIED>
<!ATTLIST skill applyExit CDATA #IMPLIED>
<!ATTLIST skill removeEnter CDATA #IMPLIED>
<!ATTLIST skill removeExit CDATA #IMPLIED>
<!ELEMENT skill EMPTY>

<!-- Settings -->
<!ATTLIST settings abnormal CDATA #IMPLIED>
<!ATTLIST settings affected (all|npc|pc|playable) #IMPLIED>
<!ATTLIST settings boss (Anakim|Antharas|Baium|Baylor|FourSepulchers|Frintezza|LastImperialTomb|Lilith|Sailren|SunLightRoom|Valakas|VanHalter|Zaken) #IMPLIED>
<!ATTLIST settings buffRepeat (true|false) #IMPLIED>
<!ATTLIST settings exitOnDeath (true|false) #IMPLIED>
<!ATTLIST settings hpDamage CDATA #IMPLIED>
<!ATTLIST settings mpDamage CDATA #IMPLIED>
<!ATTLIST settings noEscape (true|false) #IMPLIED>
<!ATTLIST settings noHeal (true|false) #IMPLIED>
<!ATTLIST settings noLanding (true|false) #IMPLIED>
<!ATTLIST settings noPrivateStore (true|false) #IMPLIED>
<!ATTLIST settings noSummon (true|false) #IMPLIED>
<!ATTLIST settings pvp (Arena|General|Peace) #IMPLIED>
<!ELEMENT settings EMPTY>

<!-- Everything below is taken from skills.dtd (should be exported to another file) -->

<!-- Condition -->
<!ATTLIST cond msg CDATA #IMPLIED>
<!ATTLIST cond msgId CDATA #IMPLIED>
<!ELEMENT cond (and|or|not|player|target|using|game)>

<!-- Logic -->
<!ELEMENT and ((and|or|not|player|target|using|game)+)>
<!ELEMENT or  ((and|or|not|player|target|using|game),(and|or|not|player|target|using|game)+)>
<!ELEMENT not (and|or|not|player|target|using|game)>

<!-- Conditions -->
<!ATTLIST player skill (true|false) #IMPLIED>
<!ATTLIST player race (Human|Elf|Darkelf|Orc|Dwarf|Kamael) #IMPLIED>
<!ATTLIST player level CDATA #IMPLIED>
<!ATTLIST player resting (true|false) #IMPLIED>
<!ATTLIST player moving (true|false) #IMPLIED>
<!ATTLIST player running (true|false) #IMPLIED>
<!ATTLIST player walking (true|false) #IMPLIED>
<!ATTLIST player behind (true|false) #IMPLIED>
<!ATTLIST player front (true|false) #IMPLIED>
<!ATTLIST player chaotic (true|false) #IMPLIED>
<!ATTLIST player olympiad (true|false) #IMPLIED>
<!ATTLIST player flying (true|false) #IMPLIED>
<!ATTLIST player hp CDATA #IMPLIED>
<!ATTLIST player mp CDATA #IMPLIED>
<!ATTLIST player cp CDATA #IMPLIED>
<!ATTLIST player attack_stance (true|false) #IMPLIED>
<!ATTLIST player grade CDATA #IMPLIED>
<!ATTLIST player siegezone CDATA #IMPLIED>
<!ATTLIST player battle_force (2|3) #IMPLIED>
<!ATTLIST player spell_force (2|3) #IMPLIED>
<!ATTLIST player weight CDATA #IMPLIED>
<!ATTLIST player invSize CDATA #IMPLIED>
<!ATTLIST player pledgeClass CDATA #IMPLIED>
<!ATTLIST player clanHall CDATA #IMPLIED>
<!ATTLIST player fort CDATA #IMPLIED>
<!ATTLIST player castle CDATA #IMPLIED>
<!ATTLIST player sex CDATA #IMPLIED>
<!ATTLIST player agathionId CDATA #IMPLIED>
<!ATTLIST player active_effect_id CDATA #IMPLIED>
<!ELEMENT player EMPTY>

<!ATTLIST target aggro (true|false) #IMPLIED>
<!ATTLIST target siegezone CDATA #IMPLIED>
<!ATTLIST target level CDATA #IMPLIED>
<!ATTLIST target class_id_restriction CDATA #IMPLIED>
<!ATTLIST target active_effect_id CDATA #IMPLIED>
<!ATTLIST target active_skill_id CDATA #IMPLIED>
<!ATTLIST target mindistance CDATA #IMPLIED>
<!ATTLIST target race_id CDATA #IMPLIED>
<!ATTLIST target undead (true|false) #IMPLIED>
<!ATTLIST target using CDATA #IMPLIED>
<!ATTLIST target npcId CDATA #IMPLIED>
<!ELEMENT target EMPTY>

<!ATTLIST using kind CDATA #IMPLIED>
<!ATTLIST using skill CDATA #IMPLIED>
<!ATTLIST using slotitem CDATA #IMPLIED>
<!ATTLIST using weaponChange (true|false) #IMPLIED>
<!ELEMENT using EMPTY>

<!ATTLIST game night (true|false) #IMPLIED>
<!ATTLIST game chance CDATA #IMPLIED>
<!ELEMENT game EMPTY>

=== FearPingWin/L2CraciaFinal/l2jfree-datapack/data/zone/clanhall.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE list SYSTEM "zones.dtd">
<list>
<!-- Retail zones. Verified by Savormix -->
  <zone id="1" name="Partisan Hideaway" type="Clanhall">
    <entity castleId="-1" clanhallId="21"/>
    <restart_owner x="43370" y="108839" z="-1980"/>
    <shape type="Poly" zMin="-2104" zMax="-1104">
      <point x="43048" y="108832"/>
      <point x="43692" y="108204"/>
      <point x="44052" y="108604"/>
      <point x="43976" y="109180"/>
      <point x="43684" y="109496"/>
    </shape>
  </zone>

  <zone id="2" name="Gludio Moonstone Hall" type="Clanhall">
    <entity castleId="1" clanhallId="22"/>
    <restart_owner x="-16029" y="123642" z="-3101"/>
    <shape type="Poly" zMin="-3598" zMax="-2098">
      <point x="-16362" y="123496"/>
      <point x="-15748" y="123315"/>
      <point x="-15645" y="123655"/>
      <point x="-16234" y="123831"/>
    </shape>
  </zone>
  <zone id="3" name="Gludio Onyx Hall" type="Clanhall">
    <entity castleId="1" clanhallId="23"/>
    <restart_owner x="-14848" y="125552" z="-3128"/>
    <shape type="Poly" zMin="-3777" zMax="-2277">
      <point x="-15098" y="125352"/>
      <point x="-14789" y="125352"/>
      <point x="-14789" y="125816"/>
      <point x="-15098" y="125816"/>
    </shape>
  </zone>
  <zone id="4" name="Gludio Topaz Hall" type="Clanhall">
    <entity castleId="1" clanhallId="24"/>
    <restart_owner x="-13879" y="125413" z="-3128"/>
    <shape type="Poly" zMin="-3745" zMax="-2245">
      <point x="-14028" y="125062"/>
      <point x="-13695" y="125070"/>
      <point x="-13695" y="125671"/>
      <point x="-14028" y="125663"/>
    </shape>
  </zone>
  <zone id="5" name="Gludio Ruby Hall" type="Clanhall">
    <entity castleId="1" clanhallId="25"/>
    <restart_owner x="-12710" y="124029" z="-3096"/>
    <shape type="Poly" zMin="-3809" zMax="-2309">
      <point x="-12942" y="123872"/>
      <point x="-12327" y="123872"/>
      <point x="-12327" y="124231"/>
      <point x="-12942" y="124231"/>
    </shape>
  </zone>
  <zone id="6" name="Gludin Crystal Hall" type="Clanhall">
    <entity castleId="1" clanhallId="26"/>
    <restart_owner x="-84416" y="152192" z="-3123"/>
    <shape type="Poly" zMin="-4706" zMax="-2576">
      <point x="-84691" y="151557"/>
      <point x="-84261" y="151557"/>
      <point x="-84260" y="152333"/>
      <point x="-84690" y="152330"/>
      <point x="-84325" y="151962"/>
      <point x="-83819" y="151959"/>
      <point x="-83819" y="152328"/>
      <point x="-84325" y="152328"/>
    </shape>
  </zone>
  <zone id="7" name="Gludin Onyx Hall" type="Clanhall">
    <entity castleId="1" clanhallId="27"/>
    <restart_owner x="-84171" y="153385" z="-3159"/>
    <shape type="Poly" zMin="-4012" zMax="-2512">
      <point x="-84000" y="154024"/>
      <point x="-84333" y="154024"/>
      <point x="-84333" y="153113"/>
      <point x="-83618" y="153100"/>
      <point x="-83618" y="153547"/>
      <point x="-84000" y="153559"/>
    </shape>
  </zone>
  <zone id="8" name="Gludin Sapphire Hall" type="Clanhall">
    <entity castleId="1" clanhallId="28"/>
    <restart_owner x="-84236" y="155520" z="-3160"/>
    <shape type="Poly" zMin="-4044" zMax="-2544">
      <point x="-84463" y="154941"/>
      <point x="-83987" y="154941"/>
      <point x="-83986" y="155688"/>
      <point x="-84463" y="155685"/>
      <point x="-84098" y="155318"/>
      <point x="-83523" y="155317"/>
      <point x="-83523" y="155686"/>
      <point x="-84098" y="155684"/>
    </shape>
  </zone>
  <zone id="9" name="Gludin Moonstone Hall" type="Clanhall">
    <entity castleId="1" clanhallId="29"/>
    <restart_owner x="-79544" y="150181" z="-3038"/>
    <shape type="Poly" zMin="-3948" zMax="-2448">
      <point x="-79657" y="149419"/>
      <point x="-79290" y="149424"/>
      <point x="-79284" y="150296"/>
      <point x="-79656" y="150298"/>
      <point x="-80066" y="149420"/>
      <point x="-79491" y="149419"/>
      <point x="-79491" y="149859"/>
      <point x="-80066" y="149857"/>
    </shape>
  </zone>
  <zone id="10" name="Gludin Emerald Hall" type="Clanhall">
    <entity castleId="1" clanhallId="30"/>
    <restart_owner x="-79513" y="151506" z="-3041"/>
    <shape type="Poly" zMin="-3980" zMax="-2480">
      <point x="-79663" y="151367"/>
      <point x="-79296" y="151372"/>
      <point x="-79290" y="152244"/>
      <point x="-79663" y="152246"/>
      <point x="-80067" y="151809"/>
      <point x="-79493" y="151808"/>
      <point x="-79493" y="152247"/>
      <point x="-80067" y="152245"/>
    </shape>
  </zone>

  <zone id="11" name="Dion Atramental Barracks Hall" type="Clanhall">
    <entity castleId="2" clanhallId="31"/>
    <restart_owner x="17760" y="145200" z="-3036"/>
    <shape type="Poly" zMin="-3365" zMax="-1865">
      <point x="17597" y="144823"/>
      <point x="17989" y="145089"/>
      <point x="17828" y="145333"/>
      <point x="17433" y="145067"/>
    </shape>
  </zone>
  <zone id="12" name="Dion Scarlet Barracks Hall" type="Clanhall">
    <entity castleId="2" clanhallId="32"/>
    <restart_owner x="18800" y="143248" z="-3010"/>
    <shape type="Poly" zMin="-3333" zMax="-1833">
      <point x="18849" y="143099"/>
      <point x="18897" y="143562"/>
      <point x="18615" y="143588"/>
      <point x="18571" y="143128"/>
    </shape>
  </zone>
  <zone id="13" name="Dion Viridian Barracks Hall" type="Clanhall">
    <entity castleId="2" clanhallId="33"/>
    <restart_owner x="20096" y="146064" z="-3111"/>
    <shape type="Rect" zMin="-3397" zMax="-1897">
      <point x="19942" y="145996"/>
      <point x="20414" y="146292"/>
    </shape>
  </zone>

  <zone id="14" name="Devastated Castle" type="Clanhall"><!-- Not Done -->
    <entity castleId="-1" clanhallId="34"/>
    <restart_chaotic x="136398" y="28901" z="-3582"/>
    <restart_chaotic x="137292" y="28485" z="-3290"/>
    <restart_chaotic x="155925" y="28554" z="-3164"/>
    <restart_chaotic x="157608" y="23866" z="-3760"/>
    <restart_chaotic x="157463" y="28770" z="-3371"/>
    <restart_chaotic x="159348" y="28561" z="-3400"/>
    <restart_chaotic x="160236" y="14119" z="-3892"/>
    <restart_chaotic x="156764" y="13774" z="-3960"/>
    <restart_chaotic x="161426" y="23055" z="-3670"/>
    <restart_chaotic x="136380" y="21899" z="-3647"/>
    <restart_chaotic x="137708" y="15640" z="-3800"/>
    <restart_owner x="146494" y="30584" z="-2420"/>
    <restart_owner x="146038" y="30519" z="-2420"/>
    <restart_owner x="148112" y="30439" z="-2420"/>
    <restart_owner x="148565" y="30463" z="-2420"/>
    <restart_owner x="150227" y="29104" z="-2420"/>
    <restart_owner x="144626" y="29145" z="-2420"/>
    <restart_owner x="144635" y="26664" z="-2220"/>
    <restart_owner x="144526" y="24661" z="-2100"/>
    <restart_owner x="144559" y="22835" z="-2100"/>
    <restart_owner x="145686" y="21114" z="-2100"/>
    <restart_owner x="148946" y="21121" z="-2070"/>
    <restart_owner x="148010" y="27996" z="-2256"/>
    <restart_owner x="147970" y="27040" z="-2191"/>
    <shape type="Poly" zMin="-2514" zMax="486">
      <point x="176793" y="-19176"/>
      <point x="179892" y="-19176"/>
      <point x="179892" y="-15276"/>
      <point x="179417" y="-14511"/>
      <point x="177270" y="-14511"/>
      <point x="176793" y="-15276"/>
    </shape>
  </zone>

  <zone id="15" name="Bandits Stronghold" type="Clanhall"><!-- Not Done -->
    <entity castleId="5" clanhallId="35"/>
    <restart_chaotic x="76576" y="50151" z="-3200"/>
    <restart_chaotic x="77310" y="50317" z="-3160"/>
    <restart_chaotic x="77250" y="51285" z="-3160"/>
    <restart_chaotic x="78811" y="51106" z="-3160"/>
    <restart_chaotic x="75755" y="51372" z="-3250"/>
    <restart_chaotic x="75613" y="52504" z="-3200"/>
    <restart_chaotic x="74459" y="52441" z="-3260"/>
    <restart_chaotic x="74467" y="53354" z="-3200"/>
    <restart_chaotic x="73600" y="53918" z="-3170"/>
    <restart_chaotic x="71102" y="57875" z="-3330"/>
    <restart_chaotic x="70052" y="59300" z="-3580"/>
    <restart_chaotic x="70420" y="57480" z="-3480"/>
    <restart_chaotic x="75474" y="60125" z="-2730"/>
    <restart_chaotic x="74880" y="60818" z="-2820"/>
    <restart_chaotic x="88011" y="56589" z="-3560"/>
    <restart_chaotic x="91239" y="53120" z="-3430"/>
    <restart_chaotic x="81785" y="46306" z="-3160"/>
    <restart_chaotic x="80708" y="44609" z="-3120"/>
    <restart_chaotic x="70139" y="55885" z="-3550"/>
    <restart_chaotic x="80236" y="45675" z="-3150"/>
    <restart_owner x="80304" y="56241" z="-1500"/>
    <restart_owner x="80594" y="55837" z="-1500"/>
    <restart_owner x="79933" y="55752" z="-1500"/>
    <restart_owner x="80267" y="55497" z="-1500"/>
    <restart_owner x="80334" y="54400" z="-1500"/>
    <restart_owner x="82445" y="56012" z="-1480"/>
    <restart_owner x="82323" y="55466" z="-1480"/>
    <restart_owner x="82880" y="55390" z="-1480"/>
    <restart_owner x="82638" y="53885" z="-1440"/>
    <restart_owner x="82552" y="53447" z="-1440"/>
    <restart_owner x="82213" y="53964" z="-1440"/>
    <restart_owner x="80054" y="53209" z="-1500"/>
    <restart_owner x="79706" y="52986" z="-1500"/>
    <restart_owner x="82123" y="53535" z="-1440"/>
    <shape type="Poly" zMin="-2920" zMax="80">
      <point x="79028" y="-17588"/>
      <point x="84640" y="-19528"/>
      <point x="86952" y="-16888"/>
      <point x="83636" y="-13448"/>
      <point x="79196" y="-13584"/>
    </shape>
  </zone>

  <zone id="16" name="Aden The Golden Chamber Hall" type="Clanhall">
    <entity castleId="5" clanhallId="36"/>
    <restart_owner x="149134" y="23140" z="-2160"/>
    <shape type="Rect" zMin="-2160" zMax="-1960">
      <point x="148844" y="22709"/>
